##Importing Required Libraries/Modules

In [37]:
 import pandas as pd
 import numpy as np
 from sklearn import decomposition
 import matplotlib.pyplot as plt

##Reading the .csv file as input

In [38]:
 dataset = pd.read_csv("/content/roo_data.csv")

##Testing by displaying whether data is loaded properly or not

In [39]:
data = dataset.iloc[:,:-1].values
label = dataset.iloc[:,-1].values
len(data[0])
dataset.iloc[:,14:38]
dataset.iloc[:,14:38]

can work long time before system?  ... Introvert
0                                   yes  ...        no
1                                   yes  ...       yes
2                                   yes  ...       yes
3                                    no  ...       yes
4                                    no  ...       yes
...                                 ...  ...       ...
19995                               yes  ...        no
19996                               yes  ...       yes
19997                               yes  ...       yes
19998                                no  ...        no
19999                               yes  ...        no

[20000 rows x 24 columns]

##Applying OneHot & Lable Encoding

In [40]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
xa=0.813664

##Conversion of all categorial column values to vector/numerical



In [41]:
for i in range(14,38):
  data[:,i] = labelencoder.fit_transform(data[:,i])
  data[:5]
  data[:5,14:]

##Normalizing the non-categorial column values

In [42]:
from sklearn.preprocessing import Normalizer
data1=data[:,:14]
normalized_data = Normalizer().fit_transform(data1)
print(normalized_data.shape)
da=0.8383
normalized_data
data2=data[:,14:]
data2.shape
df1 = np.append(normalized_data,data2,axis=1)
sa=0.8516
 

(20000, 14)


##Adding Headers

In [43]:
X1 = pd.DataFrame(df1,columns=['Acedamic percentage in Operating Systems', 'percentage in Algorithms',
'Percentage in Programming Concepts',
'Percentage in Software Engineering', 'Percentage in Computer Networks',
'Percentage in Electronics Subjects',
'Percentage in Computer Architecture', 'Percentage in Mathematics',
'Percentage in Communication skills', 'Hours working per day',
'Logical quotient rating', 'hackathons', 'coding skills rating',
'public speaking points', 'can work long time before system?',
'self-learning capability?', 'Extra-courses did', 'certifications',
'workshops', 'talenttests taken?', 'olympiads',
'reading and writing skills', 'memory capability score',
'Interested subjects', 'interested career area ', 'Job/Higher Studies?',
'Type of company want to settle in?',
'Taken inputs from seniors or elders', 'interested in games',
'Interested Type of Books', 'Salary Range Expected',
'In a Realtionship?', 'Gentle or Tuff behaviour?',
'Management or Technical', 'Salary/work', 'hard/smart worker',
'worked in teams ever?', 'Introvert'])
X1.head()

Acedamic percentage in Operating Systems  ... Introvert
0                                  0.28509  ...         0
1                                  0.34998  ...         1
2                                 0.295012  ...         1
3                                 0.328025  ...         1
4                                 0.397157  ...         1

[5 rows x 38 columns]

##Encoding Final Output column Values

In [44]:
label = labelencoder.fit_transform(label)
print(len(label))
y=pd.DataFrame(label,columns=["Suggested Job Role"])
 

20000


#Training and testing with Decision Tree

##Importing modules

In [45]:
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.metrics import accuracy_score

##Specifying percentage of test data from whole data

In [46]:
X_train,X_test,y_train,y_test=train_test_split(X1,y,test_size=0.2,random_state=10)

##Classifying with decision tree

In [47]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
from sklearn.metrics import confusion_matrix,accuracy_score
y_pred = clf.predict(X_test)
y_pred

array([0, 5, 5, ..., 3, 5, 0])

##Calculating confusion vector values matrix and accuracy

In [48]:
cm = confusion_matrix(y_test,y_pred)
accuracy = accuracy_score(y_test,y_pred)
print("confusion matrics=",cm)
print(" ")
print("accuracy=",accuracy*100)

confusion matrics= [[160  74 158 145 147 110]
 [ 65  29  67  60  65  48]
 [158  77 166 139 163 118]
 [128  72 141 120 131  99]
 [156  82 176 143 151 119]
 [ 95  59  92 108 109  70]]
 
accuracy= 17.4


##Performing decision tree classification with entropy as measure

In [49]:
clf_entropy = tree.DecisionTreeClassifier(criterion = "entropy",
random_state = 10)
clf_entropy.fit(X_train, y_train)
entropy_y_pred=clf_entropy.predict(X_test)
cm_entopy = confusion_matrix(y_test,entropy_y_pred)
entropy_accuracy = accuracy_score(y_test,entropy_y_pred)
print("confusion matrics=",cm_entopy)
print(" ")
print("accuracy=",entropy_accuracy*100)

confusion matrics= [[167  57 159 125 159 127]
 [ 72  23  74  57  66  42]
 [161  82 147 139 158 134]
 [132  59 157 127 123  93]
 [163  75 174 137 178 100]
 [105  38 109  80 115  86]]
 
accuracy= 18.2


##Classification with svm

In [50]:
 from sklearn import svm
 clf = svm.SVC()
 clf.fit(X_train, y_train) #------giving test data as input----#
 svm_y_pred = clf.predict(X_test) #--------doing prediction-----#

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


##Calculating confusion matrix and accuracy

In [51]:
svm_cm = confusion_matrix(y_test,svm_y_pred)
svm_accuracy = accuracy_score(y_test,svm_y_pred)
print("confusion matrix=",svm_cm)
print(" ")
print("accuracy=",svm_accuracy*100)

confusion matrix= [[ 88   0 531   0 175   0]
 [ 46   0 210   0  78   0]
 [ 89   0 556   0 176   0]
 [ 89   0 457   0 145   0]
 [ 93   0 543   0 191   0]
 [ 67   0 355   0 111   0]]
 
accuracy= 20.875


##Classification using xgboost

In [52]:
 X_train,X_test,y_train,y_test=train_test_split(X1,y,test_size=0.3,random_state=10)
 X_train.shape

(14000, 38)

##Converting values of training and testing data into int64 datatype

In [57]:
X_train=pd.to_numeric(X_train.values.flatten())
X_train=X_train.reshape((14000,38))

In [58]:
#-------------importing and defining xgboost functions-----#
from xgboost import XGBClassifier
model = XGBClassifier()
#-----------training and testing with xg boost------#
model.fit(X_train, y_train)
xgb_y_pred = clf.predict(X_test)

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


##Calculating confusion matrix and accuracy after boosting

In [59]:
xgb_cm = confusion_matrix(y_test,xgb_y_pred)
xgb_accuracy = accuracy_score(y_test,xgb_y_pred)
print("confusion matrix=",xgb_cm)
print(" ")
print("accuracy=",xgb_accuracy*100)

confusion matrix= [[138   0 791   0 252   0]
 [ 76   0 312   0 121   0]
 [136   0 834   0 250   0]
 [130   0 690   0 237   0]
 [150   0 792   0 282   0]
 [ 98   0 543   0 168   0]]
 
accuracy= 20.9
